server {
    listen 8002;
    root src;
	host localhost;
	index index.html;
	client_max_body_size 52428800;
	error_page 404 ola;
	error_page 405 ola;	
}
server{
	listen 8003;
    root src;
	host localhost;
	index index.html;
	client_max_body_size 52428800;
	error_page 404 ola;
	error_page 405 ola;	
}
